[package]
name = "advent_of_code_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.34"
hashbrown = "0.15.2"
rayon = "1.10.0"
regex = "1.11.1"
